config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root to: "home#index" 
  resources :users, only:[:show, :edit, :update] do
    resources :diaries
  end
  
  resources :communities do
    resources :chats
    resources :community_partcipants, only: [:index, :create, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :community
  belongs_to :user
end

app/models/community.rb
class Community < ApplicationRecord
  validates :name, presence: true
  has_many :community_partcipants, inverse_of: :community
  has_many :users, through: :community_partcipants
  has_many :chats
  
  after_create :update_admin_authority
  
  def update_admin_authority
    community_partcipant = self.community_partcipants.first
    community_partcipant.update_column(:admin, true)
  end
  
  def admin_user?(user)
    CommunityPartcipant.exists?(user_id: user.id, community_id: self.id, admin: true)
  end
end

app/models/community_partcipant.rb
class CommunityPartcipant < ApplicationRecord
  belongs_to :user, inverse_of: :community_partcipants
  belongs_to :community, inverse_of: :community_partcipants
end

app/models/community_participant.rb
class CommunityParticipant < ApplicationRecord
  belongs_to :user, inverse_of: :community_participants
  belongs_to :community, inverse_of: :community_participants
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_image, ProfileImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, on: :create
  has_many :diaries, dependent: :destroy
  
  has_many :community_partcipants, inverse_of: :user
  has_many :communities, through: :community_partcipants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]
  before_action :set_community
  
  def index
    @chats = @community.chats.page(params[:page]).per(3)
  end
  
  def show
  end
  
  def new
    @chat = @community.chats.build
  end
  
  def create
    @chat = @community.chats.build(chat_params)
    if @chat.save
      redirect_to community_path(@community)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @chat.update(chat_params)
      redirect_to community_chat_path(@community)
    else
      render :edit
    end
  end
  
  def destroy
    @chat.destroy
    redirect_to community_path(@community)
  end
 
private

  def chat_params
    params.require(:chat).permit(:title, :description).merge!(user_id: current_user.id)
  end
  
  def set_chat
    @chat = Chat.find(params[:id])
  end
  
  def set_community
    @community = Community.find(params[:community_id])
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  def index
    @communities = Community.order(id: :desc).page(params[:page]).per(3)
  end
  
  def new
    @community = current_user.communities.build
  end
  
  def create
    @community = current_user.communities.build(community_params)
    if @community.save
      redirect_to communities_path
    else
      render :new
    end
  end
  
  def show
    @community_partcipant = @community.community_partcipants.find_by(user_id: current_user.id)
  end
  
  def edit
  end
  
  def update
    if @community.update(community_params)
      redirect_to @community
    else
      render :edit
    end
  end
  
  def destroy
    @community.destroy
    redirect_to communities_path
  end
  
  private
  
  def community_params
    params.require(:community).permit(:name, :description)
  end
    
  def set_community
    @community = Community.find(params[:id])
  end
  
end

app/controllers/community_partcipants_controller.rb
class CommunityPartcipantsController < ApplicationController
  before_action :set_community
  before_action :set_community_partcipant, only: [:destroy]
  before_action :require_community_admin_user!, only: [:index, :update]

  def index
    @users = @community.users.order(id: :desc)
  end
  
  def show
    @community_participant = @comumunity.community_participants.find_by(user_id: current_user.id)
  end
  
  def create
    @community_partcipant = current_user.community_partcipants.build(community_id: params[:community_id])
    @community_partcipant.save!
    redirect_to community_path(@community)
  end
  
  def destroy
    @community_partcipant.destroy!
    redirect_to community_path(@community)
  end
  
  def update
    @community_partcipant = @community.community_partcipants.find(params[:id])
    @community_partcipant.update!(admin: true)
    redirect_to community_community_partcipants_path(@community)
  end
  
  private
  
  def set_community_partcipant
    @community_partcipant = CommunityPartcipant.find(params[:id])
  end
  
  def set_community
    @community = Community.find(params[:community_id])
  end
  
  def require_community_admin_user!
    redirect_to root_path unless Community.find(params[:community_id]).admin_user?(current_user)
  end
end

app/controllers/community_participants_controller.rb
class CommunityParticipantsController < ApplicationController
  before_action :require_community_admin_user!
  before_action :set_community, only: [:index, :update]

  def index
    @users = @community.users.order(id: :desc)
  end

  def update
    @community_participant = @community.community_participants.find(params[:id])
    @community_participant.update!(admin: true)
    redirect_to community_community_participants_path(@community)
  end

  private

  def set_community
    @community = Community.find(params[:community_id])
  end

  def require_community_admin_user!
    redirect_to root_path unless Community.find(params[:community_id]).admin_user?(current_user)
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :set_user_diary, only: [:index]

  def index
    @diaries = @user.diaries.page(params[:page]).per(3)
  end
  
  def show
  end
  
  def new
    @diary = current_user.diaries.build
  end
  
  def create
    @diary = current_user.diaries.build(diary_params)
    if @diary.save
      redirect_to user_diary_path
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @diary.update(diary_params)
      redirect_to user_diary_path
    else
      render :edit
    end
  end
  
  def destroy
    @diary.destroy
    redirect_to user_diaries_path
  end
  
  private
    def diary_params
      params.require(:diary).permit(:title, :content).merge!(user_id: current_user.id)
    end

    def set_diary
      @diary = current_user.diaries.find(params[:id])
    end

    def set_user_diary
      @user = User.find(params[:user_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :description, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/community_partcipants_helper.rb
module CommunityPartcipantsHelper
end

app/helpers/community_participants_helper.rb
module CommunityParticipantsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_form.html.erb
<%= form_for [@community, @chat] do |f| %>
  <div class="form_gruop">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control chat__input-title' %>
  </div>
  <div class="form_gruop">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control chat__input-description' %>
  </div>
  <div class="chat__input-submit">
    <%= f.submit '作成する', class: "btn btn-success" %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<div class="container">
  <h2>チャットを編集する</h2>
  <%= render 'form' %>
</div>

app/views/chats/new.html.erb
<div class="container">
  <h2>チャットを作成する</h2>
  <%= render 'form' %>
</div>

app/views/chats/show.html.erb
<div class="container">
  <div class="chat__show-button">
    <% if @chat.user_id == current_user.id %>
      <%= link_to '編集する', edit_community_chat_path(@community), class: "btn btn-success" %>　
      <%= link_to '削除する', community_chat_path(@community), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>　
    <% end %>
    <%= link_to 'コミュニティに戻る', community_path(@community), class: "btn btn-info" %>
  </div>
  <div class="card">
    <div class="card-header">
      タイトル　<%= @chat.title %><br>
      投稿者　　<%= @chat.user.name %>さん
    </div>
    <div class="card-body">
      <%= @chat.description %>
    </div>
  </div>
</div>

app/views/communities/_form.html.erb
<% @community.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>
<%= form_for @community do |f| %>
  <div class="form_group">
    <%= f.label :コミュニティ名 %>
    <%= f.text_field :name, class: 'form-control community__input-name' %>
  </div>
  <div class="form_group">
    <%= f.label :説明 %>
    <%= f.text_area :description, class: 'form-control community__input-description' %>
  </div>
  <div class="community__input-submit">
    <%= f.submit "作成する", class: "btn btn-success" %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<div class="container">
  <h2 class="community__edit-title">コミュニティを編集する</h2>
  <%= render 'form' %>
</div>

app/views/communities/index.html.erb
<div class="container">
  <%= link_to 'コミュニテイを作成する', new_community_path, class: "btn btn-primary community__index-button" %>
  <h2 class="community__title">コミュニティ一覧</h2>
  <div class="community__index">
    <% @communities.each do |community| %>
      <div class="card community__card" style="width: 18rem;">
        <div class="card-header">
          <%= community.name %>
          <% if community.admin_user?(current_user) %>
            <span class="badge badge-primary float-right">管理者</span>
          <% end %>
        </div>
        <div class="card-body community__card-body">
          <div class="card-text"><%= community.description %></div>
          <div class="community__card-body-btn-wrapper">
            <%= link_to 'コミュニティ詳細', community_path(community), class: "btn btn-outline-info btn-sm" %>　
            <% if community.admin_user?(current_user) %>
              <%= link_to 'ユーザー一覧', community_community_partcipants_path(community), class: "btn btn-outline-primary btn-sm" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @communities %>
</div>

app/views/communities/new.html.erb
<div class="container">
  <h2 class="community__new-title">コミュニティ作成</h2>
  <%= render 'form' %>
</div>

app/views/communities/show.html.erb
<div class="container">
  <div class="community__show-button">
    <% if !@community.admin_user?(current_user) %>
      <% if CommunityPartcipant.exists?(user_id: current_user.id, community_id: @community.id)%>
        <%= link_to 'コミュニティを退会する', community_community_partcipant_path(@community, @community_partcipant), method: :delete, class: "btn btn-danger" %>　
      <% else %>
        <%= link_to 'コミュニテイに参加する', community_community_partcipants_path(@community), method: :post, class: "btn btn-primary" %>　
      <% end %>
    <% end %>
    <% if @community.admin_user?(current_user) %>
      <%= link_to 'コミュニティを編集する', edit_community_path(@community), class: "btn btn-primary" %>　
      <%= link_to 'コミュニティを削除する', community_path(@community), method: :delete, data: { confirm: '本当にコミュニティを削除しますか？' },class: "btn btn-danger"  %>　
    <% end %>
    <%= link_to 'コミュニテイ一覧に戻る', communities_path, class: "btn btn-info" %>
  </div>
  <div class="community__title">
    <h2>コミュニティ名</h2>
    <h2 style="text-decoration:underline"><%= @community.name %></h2>
  </div>
  <div class="card community__sidebar">
    <div class="card-header">
      管理人　<%= @community.community_partcipants.first.user.name %>　さん
    </div>
    <div class="card-body">
      <p>メンバー数　<%= CommunityPartcipant.where(community_id: @community.id).count %>人</p>
      <p>開設日　<%= @community.created_at.strftime('%Y年%m月%d日')  %></p>
    </div>
  </div>
  <div class="community__information">
    <div class="card community__show-card">
      <div class="card-header">コミュニティ詳細</div>
      <div class="card-body">
        <p class="card-text"><%= @community.description %></p>
      </div>
    </div>
    <div class="community__show-chat">
      <h3 class="community__show-chat-title">
        スレッド一覧
      </h3>
      <div class="community__show-card-chat-title-button">
        <% if CommunityPartcipant.exists?(user_id: current_user.id, community_id: @community.id)%>
          <%= link_to '新しいスレッドを作成する', new_community_chat_path(@community), class: "btn btn-primary" %>
        <% end %>
      </div>
      <% if @community.chats.exists? %>
        <% @community.chats.each do |chat| %>
          <div class="card community__show-card-chat">
            <div class="card-header">
              タイトル　<%= chat.title %><br>
              投稿者　　<%= chat.user.name %>さん
            </div>
            <div class="card-body">
              <div class="card-text"><%= chat.description %></div>
              <div class="community__show-card-chat-button">
                <%= link_to 'スレッド詳細', community_chat_path(@community, chat.id), class: "btn btn-info" %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class= "community__show-chat-info">作成されたスレッドはありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/community_partcipants/index.html.erb
<div class="container">
  <div class ="community_partcipant__index-button">
    <%= link_to 'コミュニティ一覧に戻る', communities_path, class: "btn btn-info" %>
  </div>
  <% @users.each do |user| %>
    <div class="card d-link-block">
      <div class="card-header text-center font-weight-bold">
        <%= user.name %>
      </div>
      <div class="card-body text-center">
        <%= image_tag 'https://www.gyomy.com/images/user-300.png', size: '100', class: 'd-block mb-3', style: "margin: 0 auto;" %>
        <% if @community.admin_user?(user) %>
          <span class="btn btn-sm btn-outline-warning pl-4 pr-4">管理者</span>
    　  <% else %>
    　    <% community_partcipant = @community.community_partcipants.find_by(user_id: user.id) %>
    　    <%= link_to '管理者にする', community_community_partcipant_path(@community, community_partcipant), method: :patch, size: '100', class: 'btn btn-sm btn-outline-info' %>
    　  <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/community_participants/index.html.erb
<div class="container">
  <% @users.each do |user| %>
    <div class="card d-inline-block">
      <div class="card-header text-center font-weight-bold">
        <%= user.name %>
      </div>
      <div class="card-body text-center">
        <%= image_tag 'https://www.gyomy.com/images/user-300.png', size: '100', class: 'd-block mb-3', style: "margin: 0 auto;" %>
        <% if @community.admin_user?(user) %>
          <span class="btn btn-sm btn-outline-warning pl-4 pr-4">管理者</span>
        <% else %>
          <% community_participant = @community.community_participants.find_by(user_id: user.id) %>
          <%= link_to '管理者にする', community_community_participant_path(@community, community_participant), method: :patch, size: '100', class: 'btn btn-sm btn-outline-info' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/diaries/_form.html.erb
<% @diary.errors.full_messages.each do |message| %>
  <%= message %>
<% end %>
<%= form_for [current_user, @diary] do |f| %>
  <div class="form_group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control diary__input-title' %>
  </div>
  <div class="form_group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control diary__input-content' %>
  </div>
  <div class="diary__input-submit">
    <%= f.submit "投稿する", class: "btn btn-success" %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<div class="container">
  <h2>日記を編集する</h2>
  <%= render 'form' %>
</div>

app/views/diaries/index.html.erb
<div class="container">
  <%= link_to '日記を書く', new_user_diary_path, class: "btn btn-primary diary__index-button" %>　
  <h2 class="diary__title">日記一覧</h2>
  <div class="diary__index">
    <% if @user.diaries.exists? %>
      <% @diaries.each do |diary| %>
        <div class="card diary__card" style="width: 18rem;">
          <div class="card-body diary__card-body">
            <h5 class="card-title"><%= truncate(diary.title, length: 20) %></h5>
            <p class="card-text"><p><%= truncate(diary.content, length: 100) %></p>
            <%= link_to '日記を見る', user_diary_path(@user, id: diary), class: "btn btn-info diary__card-button" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>まだ日記はありません</p>
    <% end %>
  </div>
  <%= paginate @diaries %>
</div>

app/views/diaries/new.html.erb
<div class="container">
  <h2>日記を書く</h2>
  <%= render 'form' %>
</div>

app/views/diaries/show.html.erb
<div class="container">
  <div class="diary__show-button">
    <%= link_to '日記一覧に戻る', user_diaries_path, class: "btn btn-secondary" %>　
    <%= link_to '編集',edit_user_diary_path(@diary), class:"btn btn-primary" %>　 
    <%= link_to '削除',user_diary_path(@diary), method: :delete, data: { confirm: '本当に削除しますか？' },class:"btn btn-danger" %>
  </div>
  <div class="card">
    <div class="card-header">
      <h3><%= @diary.title %></h3>
      <h5><%= @diary.created_at.strftime('%Y年%m月%d日 %H:%M') %></h5>
    </div>
    <div class="card-body">
      <h5 class="card-text"><%= @diary.content %></h5>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control user__input-name' %>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control user__input-description'  %>
    <%= f.file_field :profile_image %>
    <div class="user__input-submit">
      <%= f.submit "更新する", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user__container">
  <div class="user__sidebar">
    <div class="card bg-light mb-3 user__card-friend" style="max-width: 25rem;">
      <div class="card-header"><h5>マイフレンド一覧</h5></div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <h5 class="card-text"></h5>
      </div>
    </div>
    <div class="card bg-light mb-3 user__card-community" style="max-width: 25rem;">
      <div class="card-header"><h5>マイコミュニティ</h5></div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <h5 class="card-text"></h5>
      </div>
    </div>
    <div class="card bg-light mb-3 user__card-diary" style="max-width: 25rem;">
      <div class="card-header"><h5>日記</h5></div>
      <div class="card-body">
        <div class="card-text">
          <div class="card diary__card" style="width: 18rem;">
            <div class="card-body diary__card-body">
              <% if @user.diaries.exists? %>
                <h5 class="card-title"><%= truncate(@user.diaries.last.title, length: 20) %></h5>
                <p class="card-text"><p><%= truncate(@user.diaries.last.content, length: 100) %></p>
                <%= link_to '最新の日記を見る', user_diary_path(@user, @user.diaries.last), class: "btn btn-primary diary__card-button" %>
              <% else %>
                <p>まだ日記はありません。</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="user__diary-button">
          <% if @user.diaries.exists? %>
            <%= link_to '他の日記はこちら', user_diaries_path(@user), class: "btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="user__profile">
    <div class="card user__profile-card-image" style="width: 25rem;">
　    <% if @user.profile_image.present? %>
　      <%= image_tag @user.profile_image.url, class:"user__profile-image-tag" %>
　    <% else %>
　      <%= image_tag "default.jpg", class:"user__profile-image-tag" %>
　    <% end %>
      <div class="card-body">
        <p class="card-text text-center"><%= @user.name %>さん</p>
      </div>
    </div>
    <div class="card bg-light mb-3 user__card-profile" style="max-width: 25rem;">
      <div class="card-header"><h5>自己紹介</h5></div>
      <div class="card-body">
        <h5 class="card-text"><%= current_user.description %></h5>
      </div>
    </div>
  </div>
</div>